apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-child
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/davidpb246/argocd-examples'
    targetRevision: 'main'  # o '1.0.0' si es una rama o tag
    path: charts/apache      # ruta dentro del repo donde está el chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
